### ISSUE TITLE
该插件_可能_在安装者不知情时更改界面语言

### ISSUE THREAD

**Issue by ChengduLittleA** [Mister-Kin/ToggleLanguage#4] opened 2024-09-02 04:36 UTC
收到报告称意外安装的语言相关插件可在用户不知情时更改界面语言。

由于该插件为目前已知的位于extension platform的涉及汉语翻译功能的插件之一，建议检查该插件的运行情况，并建议将默认语言均设置为英语。

请参阅该汇报：https://projects.blender.org/blender/blender/issues/127034

谢谢！

**Comment by Mister-Kin** [comment] 2024-09-17 21:31
`downloaded all the extensions` is not a good idea when you don't know the addon function, just like you said in the [original issue reply](https://projects.blender.org/blender/blender/issues/127034#issuecomment-1283998). 

Since you reported this problem here, I would simply introduce you to code design of `Toggle Language feature` to help you understand `Toggle Language` quickly.

`Toggle Language feature` is implemented by a blender operator which bl_idname is `toggle_language.toggle_language`. It's designed to toggle UI bletween two languages easily. The default values of two languages are `English (English)` and `Simplified Chinese (简体中文)`.

The addon offers two ways to execute the operator `toggle_language.toggle_language`. 
1. One is click directly `toggle` button using left mouse click. 
2. The other is `F5` hotkey. 

Most importantly, operator `toggle_language.toggle_language` won't auto execute by addon itself. Also those two ways needs user input for triggering execution.

`Toggle Language feature` related code includes:
- Toggle button UI: [draw_ui function](https://github.com/Mister-Kin/ToggleLanguage/blob/0df869681d57bb1198c8d9c9fae82701483ad923/ui.py#L9) in `ui.py`
- Operators definition: [TOGGLE_LANGUAGE_OT_toggle_language class](https://github.com/Mister-Kin/ToggleLanguage/blob/0df869681d57bb1198c8d9c9fae82701483ad923/operators.py#L16-L63) in `operators.py`
- Language list enum definition: [enum_languages and enum_languages_before_v4](https://github.com/Mister-Kin/ToggleLanguage/blob/0df869681d57bb1198c8d9c9fae82701483ad923/properties.py#L6-L45) in `properties.py`
- Two languages EnumProperty definition: [first_lang, first_lang_before_v4, second_lang and second_lang_before_v4](https://github.com/Mister-Kin/ToggleLanguage/blob/0df869681d57bb1198c8d9c9fae82701483ad923/properties.py#L83-L109) in `properties.py`
- Two languages EnumProperty UI: [draw function of ToggleLanguagePreferences class](https://github.com/Mister-Kin/ToggleLanguage/blob/0df869681d57bb1198c8d9c9fae82701483ad923/properties.py#L146-L159) in `properties.py`
- Hotkey definition: [register_keymaps function](https://github.com/Mister-Kin/ToggleLanguage/blob/0df869681d57bb1198c8d9c9fae82701483ad923/keymaps.py#L9-L13) in `keymaps.py`

In my opinion, the original reporter of that issue might press F5 key by accident to trigger operator execution. 

In summery, I don't think there is a problem with the `Toggle Language feature` of the addon. Therefore, I will close this issue.

If there are clear reproduction steps about this problem caused by `Toggle Language` addon, welcome to re-open this issue and discuss with me.

**Closed as completed by Mister-Kin** 2024-09-17 21:31 UTC
